<?php
/**
 * BaseChannelModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  GPH
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * giphy-api
 *
 * Giphy's public api.
 *
 * OpenAPI spec version: 0.9.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace GPH;

/**
 * BaseChannelModelTest Class Doc Comment
 *
 * @category    Class */
// * @description BaseChannelModel
/**
 * @package     GPH
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BaseChannelModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "BaseChannelModel"
     */
    public function testBaseChannelModel()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "parent"
     */
    public function testPropertyParent()
    {

    }

    /**
     * Test attribute "create_datetime"
     */
    public function testPropertyCreateDatetime()
    {

    }

    /**
     * Test attribute "breadcrumbs"
     */
    public function testPropertyBreadcrumbs()
    {

    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {

    }

    /**
     * Test attribute "slug"
     */
    public function testPropertySlug()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "short_title"
     */
    public function testPropertyShortTitle()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "featured_gif"
     */
    public function testPropertyFeaturedGif()
    {

    }

    /**
     * Test attribute "banner_image"
     */
    public function testPropertyBannerImage()
    {

    }

    /**
     * Test attribute "avatar_image"
     */
    public function testPropertyAvatarImage()
    {

    }

    /**
     * Test attribute "screensaver_gif"
     */
    public function testPropertyScreensaverGif()
    {

    }

    /**
     * Test attribute "is_private"
     */
    public function testPropertyIsPrivate()
    {

    }

    /**
     * Test attribute "is_live"
     */
    public function testPropertyIsLive()
    {

    }

    /**
     * Test attribute "event_start_datetime"
     */
    public function testPropertyEventStartDatetime()
    {

    }

    /**
     * Test attribute "event_end_datetime"
     */
    public function testPropertyEventEndDatetime()
    {

    }

    /**
     * Test attribute "has_children"
     */
    public function testPropertyHasChildren()
    {

    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {

    }

    /**
     * Test attribute "website_url"
     */
    public function testPropertyWebsiteUrl()
    {

    }

    /**
     * Test attribute "instagram_url"
     */
    public function testPropertyInstagramUrl()
    {

    }

    /**
     * Test attribute "twitter_url"
     */
    public function testPropertyTwitterUrl()
    {

    }

    /**
     * Test attribute "facebook_url"
     */
    public function testPropertyFacebookUrl()
    {

    }

    /**
     * Test attribute "pinterest_url"
     */
    public function testPropertyPinterestUrl()
    {

    }

    /**
     * Test attribute "tumblr_url"
     */
    public function testPropertyTumblrUrl()
    {

    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {

    }

    /**
     * Test attribute "trending_tags"
     */
    public function testPropertyTrendingTags()
    {

    }

    /**
     * Test attribute "gifs"
     */
    public function testPropertyGifs()
    {

    }

}
