<?php
/**
 * GifImagesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  GPH
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * giphy-api
 *
 * Giphy's public api.
 *
 * OpenAPI spec version: 0.9.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace GPH;

/**
 * GifImagesTest Class Doc Comment
 *
 * @category    Class */
// * @description An object containing data for various available formats and sizes of this GIF.
/**
 * @package     GPH
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GifImagesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GifImages"
     */
    public function testGifImages()
    {

    }

    /**
     * Test attribute "fixed_height"
     */
    public function testPropertyFixedHeight()
    {

    }

    /**
     * Test attribute "fixed_height_still"
     */
    public function testPropertyFixedHeightStill()
    {

    }

    /**
     * Test attribute "fixed_height_downsampled"
     */
    public function testPropertyFixedHeightDownsampled()
    {

    }

    /**
     * Test attribute "fixed_width"
     */
    public function testPropertyFixedWidth()
    {

    }

    /**
     * Test attribute "fixed_width_still"
     */
    public function testPropertyFixedWidthStill()
    {

    }

    /**
     * Test attribute "fixed_width_downsampled"
     */
    public function testPropertyFixedWidthDownsampled()
    {

    }

    /**
     * Test attribute "fixed_height_small"
     */
    public function testPropertyFixedHeightSmall()
    {

    }

    /**
     * Test attribute "fixed_height_small_still"
     */
    public function testPropertyFixedHeightSmallStill()
    {

    }

    /**
     * Test attribute "fixed_width_small"
     */
    public function testPropertyFixedWidthSmall()
    {

    }

    /**
     * Test attribute "fixed_width_small_still"
     */
    public function testPropertyFixedWidthSmallStill()
    {

    }

    /**
     * Test attribute "downsized"
     */
    public function testPropertyDownsized()
    {

    }

    /**
     * Test attribute "downsized_still"
     */
    public function testPropertyDownsizedStill()
    {

    }

    /**
     * Test attribute "downsized_large"
     */
    public function testPropertyDownsizedLarge()
    {

    }

    /**
     * Test attribute "downsized_medium"
     */
    public function testPropertyDownsizedMedium()
    {

    }

    /**
     * Test attribute "downsized_small"
     */
    public function testPropertyDownsizedSmall()
    {

    }

    /**
     * Test attribute "original"
     */
    public function testPropertyOriginal()
    {

    }

    /**
     * Test attribute "original_still"
     */
    public function testPropertyOriginalStill()
    {

    }

    /**
     * Test attribute "looping"
     */
    public function testPropertyLooping()
    {

    }

    /**
     * Test attribute "preview"
     */
    public function testPropertyPreview()
    {

    }

    /**
     * Test attribute "preview_gif"
     */
    public function testPropertyPreviewGif()
    {

    }

}
