<?php
/**
 * GifImagesFixedWidthTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  GPH
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * giphy-api
 *
 * Giphy's public api.
 *
 * OpenAPI spec version: 0.9.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace GPH;

/**
 * GifImagesFixedWidthTest Class Doc Comment
 *
 * @category    Class */
// * @description Data surrounding versions of this GIF with a fixed width of 200 pixels. Good for mobile use.
/**
 * @package     GPH
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GifImagesFixedWidthTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GifImagesFixedWidth"
     */
    public function testGifImagesFixedWidth()
    {

    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {

    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {

    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {

    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {

    }

    /**
     * Test attribute "mp4"
     */
    public function testPropertyMp4()
    {

    }

    /**
     * Test attribute "mp4_size"
     */
    public function testPropertyMp4Size()
    {

    }

    /**
     * Test attribute "webp"
     */
    public function testPropertyWebp()
    {

    }

    /**
     * Test attribute "webp_size"
     */
    public function testPropertyWebpSize()
    {

    }

}
