<?php
/**
 * GifImagesLoopingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  GPH
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * giphy-api
 *
 * Giphy's public api.
 *
 * OpenAPI spec version: 0.9.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace GPH;

/**
 * GifImagesLoopingTest Class Doc Comment
 *
 * @category    Class */
// * @description Data surrounding a version of this GIF set to loop for 15 seconds.
/**
 * @package     GPH
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GifImagesLoopingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GifImagesLooping"
     */
    public function testGifImagesLooping()
    {

    }

    /**
     * Test attribute "mp4"
     */
    public function testPropertyMp4()
    {

    }

}
