<?php
/**
 * GifTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  GPH
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * giphy-api
 *
 * Giphy's public api.
 *
 * OpenAPI spec version: 0.9.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace GPH;

/**
 * GifTest Class Doc Comment
 *
 * @category    Class */
// * @description An object containing data that describes GIFs returned by the query.
/**
 * @package     GPH
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GifTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Gif"
     */
    public function testGif()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "slug"
     */
    public function testPropertySlug()
    {

    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {

    }

    /**
     * Test attribute "bitly_gif_url"
     */
    public function testPropertyBitlyGifUrl()
    {

    }

    /**
     * Test attribute "bitly_url"
     */
    public function testPropertyBitlyUrl()
    {

    }

    /**
     * Test attribute "embed_url"
     */
    public function testPropertyEmbedUrl()
    {

    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {

    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {

    }

    /**
     * Test attribute "rating"
     */
    public function testPropertyRating()
    {

    }

    /**
     * Test attribute "content_url"
     */
    public function testPropertyContentUrl()
    {

    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {

    }

    /**
     * Test attribute "featured_tags"
     */
    public function testPropertyFeaturedTags()
    {

    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {

    }

    /**
     * Test attribute "source_tld"
     */
    public function testPropertySourceTld()
    {

    }

    /**
     * Test attribute "source_post_url"
     */
    public function testPropertySourcePostUrl()
    {

    }

    /**
     * Test attribute "is_hidden"
     */
    public function testPropertyIsHidden()
    {

    }

    /**
     * Test attribute "is_removed"
     */
    public function testPropertyIsRemoved()
    {

    }

    /**
     * Test attribute "is_community"
     */
    public function testPropertyIsCommunity()
    {

    }

    /**
     * Test attribute "is_anonymous"
     */
    public function testPropertyIsAnonymous()
    {

    }

    /**
     * Test attribute "is_featured"
     */
    public function testPropertyIsFeatured()
    {

    }

    /**
     * Test attribute "is_realtime"
     */
    public function testPropertyIsRealtime()
    {

    }

    /**
     * Test attribute "is_indexable"
     */
    public function testPropertyIsIndexable()
    {

    }

    /**
     * Test attribute "is_sticker"
     */
    public function testPropertyIsSticker()
    {

    }

    /**
     * Test attribute "update_datetime"
     */
    public function testPropertyUpdateDatetime()
    {

    }

    /**
     * Test attribute "create_datetime"
     */
    public function testPropertyCreateDatetime()
    {

    }

    /**
     * Test attribute "import_datetime"
     */
    public function testPropertyImportDatetime()
    {

    }

    /**
     * Test attribute "trending_datetime"
     */
    public function testPropertyTrendingDatetime()
    {

    }

    /**
     * Test attribute "images"
     */
    public function testPropertyImages()
    {

    }

}
