<?php
/**
 * RandomGifTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  GPH
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * giphy-api
 *
 * Giphy's public api.
 *
 * OpenAPI spec version: 0.9.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace GPH;

/**
 * RandomGifTest Class Doc Comment
 *
 * @category    Class */
// * @description An object containing data that describes GIFs returned by the query.
/**
 * @package     GPH
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RandomGifTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RandomGif"
     */
    public function testRandomGif()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {

    }

    /**
     * Test attribute "image_original_url"
     */
    public function testPropertyImageOriginalUrl()
    {

    }

    /**
     * Test attribute "image_url"
     */
    public function testPropertyImageUrl()
    {

    }

    /**
     * Test attribute "image_mp4_url"
     */
    public function testPropertyImageMp4Url()
    {

    }

    /**
     * Test attribute "image_frames"
     */
    public function testPropertyImageFrames()
    {

    }

    /**
     * Test attribute "image_width"
     */
    public function testPropertyImageWidth()
    {

    }

    /**
     * Test attribute "image_height"
     */
    public function testPropertyImageHeight()
    {

    }

    /**
     * Test attribute "fixed_height_downsampled_url"
     */
    public function testPropertyFixedHeightDownsampledUrl()
    {

    }

    /**
     * Test attribute "fixed_height_downsampled_width"
     */
    public function testPropertyFixedHeightDownsampledWidth()
    {

    }

    /**
     * Test attribute "fixed_height_downsampled_height"
     */
    public function testPropertyFixedHeightDownsampledHeight()
    {

    }

    /**
     * Test attribute "fixed_width_downsampled_url"
     */
    public function testPropertyFixedWidthDownsampledUrl()
    {

    }

    /**
     * Test attribute "fixed_width_downsampled_width"
     */
    public function testPropertyFixedWidthDownsampledWidth()
    {

    }

    /**
     * Test attribute "fixed_width_downsampled_height"
     */
    public function testPropertyFixedWidthDownsampledHeight()
    {

    }

    /**
     * Test attribute "fixed_height_small_url"
     */
    public function testPropertyFixedHeightSmallUrl()
    {

    }

    /**
     * Test attribute "fixed_height_small_still_url"
     */
    public function testPropertyFixedHeightSmallStillUrl()
    {

    }

    /**
     * Test attribute "fixed_height_small_width"
     */
    public function testPropertyFixedHeightSmallWidth()
    {

    }

    /**
     * Test attribute "fixed_height_small_height"
     */
    public function testPropertyFixedHeightSmallHeight()
    {

    }

    /**
     * Test attribute "fixed_width_small_url"
     */
    public function testPropertyFixedWidthSmallUrl()
    {

    }

    /**
     * Test attribute "fixed_width_small_still_url"
     */
    public function testPropertyFixedWidthSmallStillUrl()
    {

    }

    /**
     * Test attribute "fixed_width_small_width"
     */
    public function testPropertyFixedWidthSmallWidth()
    {

    }

    /**
     * Test attribute "fixed_width_small_height"
     */
    public function testPropertyFixedWidthSmallHeight()
    {

    }

}
