<?php
/**
 * UserTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  GPH
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * giphy-api
 *
 * Giphy's public api.
 *
 * OpenAPI spec version: 0.9.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace GPH;

/**
 * UserTest Class Doc Comment
 *
 * @category    Class */
// * @description An object containing data about the user associated with this GIF, if applicable.
/**
 * @package     GPH
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "User"
     */
    public function testUser()
    {

    }

    /**
     * Test attribute "avatar_url"
     */
    public function testPropertyAvatarUrl()
    {

    }

    /**
     * Test attribute "banner_url"
     */
    public function testPropertyBannerUrl()
    {

    }

    /**
     * Test attribute "profile_url"
     */
    public function testPropertyProfileUrl()
    {

    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {

    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {

    }

    /**
     * Test attribute "twitter"
     */
    public function testPropertyTwitter()
    {

    }

}
